version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli@10.2.3
      - npm install
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - aws s3 sync dist/ s3://sistemacoopeumo-s3-bucket --delete